Repository Codeit3-part3-team4/Taskify, pull requests merged in 2024-03, with the labels that each got.

#5 setting : convention.md 파일 추가
  CONVENTION.md
  package-lock.json
Labels: documentation

#17 [TK-16] feat: 랜딩페이지 레이아웃 기본
  public/images/facebook.svg
  public/images/instagram.svg
  public/images/mail.svg
  public/images/taskify-logo-dark.svg
  public/images/taskify-logo-light.svg
  src/app/(home)/components/Footer.tsx
  src/app/(home)/components/Landing.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/components/header/Header.tsx
Labels: enhancement

#29 [TK-2] dashboard, mydashboard layout 설정
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/mydashboard/components/DashboarderMaker/ColorPicker.tsx
  src/app/dashboard/mydashboard/components/DashboarderMaker/ColorSelectButton.tsx
  src/app/dashboard/mydashboard/components/DashboarderMaker/DashboardNameInput.tsx
  src/app/dashboard/mydashboard/components/DashboarderMaker/Dashboardmaker.tsx
  src/app/dashboard/mydashboard/components/InvitationDashboard/InvitationDashboard.tsx
  src/app/dashboard/mydashboard/components/InvitationDashboard/InvitationList.tsx
  src/app/dashboard/mydashboard/components/InvitationDashboard/SearchForm.tsx
  src/app/dashboard/mydashboard/components/MydashboardSection/AddDashboardButton.tsx
  src/app/dashboard/mydashboard/components/MydashboardSection/DashboardCard.tsx
  src/app/dashboard/mydashboard/components/MydashboardSection/DashboardInf.tsx
  src/app/dashboard/mydashboard/components/MydashboardSection/DashboardList.tsx
  src/app/dashboard/mydashboard/components/MydashboardSection/MyDashboardPage.tsx
  src/app/dashboard/mydashboard/components/MydashboardSection/MyDashboardSection.tsx
  src/app/dashboard/mydashboard/components/MydashboardSection/Pagination.tsx
  src/app/dashboard/mydashboard/page.tsx
Labels: enhancement

#30 [TK-2] mydashboard 관련 경로 수정
  src/components/SideDashboardList/SideDashboardList.tsx
Labels: bug

#40 [Tk 39] 계정 정보 페이지에 로그인 정보 불러오기
  src/api/loginApi.ts
  src/api/userApi.ts
  src/app/mypage/page.tsx
  src/components/mypage/myaccounts.tsx
  src/context/UserContext.ts
Labels: enhancement

#41 [Tk 39] 계정 관리 페이지 기능 구현
  public/images/basic-profile.svg
  public/images/password-eyes.svg
  public/images/taskify-logo-main.svg
  src/api/loginApi.ts
  src/api/userApi.ts
  src/app/mypage/page.tsx
  src/components/mypage/myaccounts.tsx
Labels: enhancement

#42 [TK-24] 카드, 컬럼 컴포넌트 수정
  public/images/calendar-icon.svg
  public/images/image-test.png
  public/images/purple-dot.svg
  public/images/settings.svg
  src/api/dashboardsApi.ts
  src/api/getCardListApi.ts
  src/api/getColumnListApi.ts
  src/app/(home)/page.tsx
  src/components/card/Card.tsx
  src/components/column/Column.tsx
  src/components/getCard/GetCard.tsx
  src/components/getColumnData.tsx/GetColumnData.tsx
Labels: enhancement

#44 [TK-35] 대시보드 수정하기 반응형 및 api 연결
  public/images/add-white.svg
  src/api/dashboardsApi.ts
  src/api/membersApi.ts
  src/app/(home)/components/Landing.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardBack.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardDelete.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardName.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteList.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/app/dashboard/[id]/edit/page.tsx
  src/app/dashboard/mydashboard/(components)/DashboarderMaker/Dashboardmaker.tsx
  src/components/hooks/useMediaQuery.ts
  tailwind.config.ts
Labels: enhancement

#45 [TK-43] 카드, 컬럼 api 수정
  src/api/cardApi.ts
  src/api/columnApi.ts
  src/api/getCardListApi.ts
  src/api/getColumnListApi.ts
  src/components/column/Column.tsx
  src/components/getCard/GetCard.tsx
  src/components/getColumnData.tsx/GetColumnData.tsx
Labels: enhancement

#48 [TK-46] 대시보드 수정 완료
  .prettierrc
  src/api/InvitationApi.ts
  src/api/cardApi.ts
  src/api/columnApi.ts
  src/api/dashboardsApi.ts
  src/api/loginApi.ts
  src/api/membersApi.ts
  src/api/signupApi.ts
  src/api/userApi.ts
  src/app/dashboard/[id]/edit/(Components)/DashboardBack.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardDelete.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardName.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteList.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteModal.tsx
  src/app/dashboard/[id]/edit/(Components)/LinkComponents.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/app/dashboard/[id]/edit/page.tsx
  src/app/dashboard/[id]/page.tsx
  src/components/Modal/Modal.tsx
Labels: enhancement

#56 [Tk 3] 로그인 페이지 기능 구현
  src/api/AuthApi.ts
  src/api/signupApi.ts
  src/api/userApi.ts
  src/app/login/components/Login.tsx
  src/app/login/page.tsx
  src/app/signup/components/Signup.tsx
  src/app/signup/page.tsx
  src/components/login/LoginLink.tsx
  src/components/login/MainLogo.tsx
  src/components/login/UserValueInput.tsx
  src/components/login/login.tsx
Labels: enhancement

#58 TK-57: 쿠키를 이용한 accessToken 저장
  src/api/AuthApi.ts
  src/api/dashboardsApi.ts
  src/app/(home)/components/Landing.tsx
  src/app/api/cookies/route.ts
  src/app/dashboard/[id]/edit/(Components)/DashboardName.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/app/dashboard/layout.tsx
  src/app/login/components/Login.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
Labels: enhancement

#62 [TK-20] 카드, 컬럼 컴포넌트 반응형, 모달 연결
  src/api/cardApi.ts
  src/api/cards.ts
  src/api/columnApi.ts
  src/app/(home)/page.tsx
  src/app/column/page.tsx
  src/app/dashboard/[id]/page.tsx
  src/components/Modal/Modal.tsx
  src/components/Todo/TodoCard.tsx
  src/components/Todo/TodoForm.tsx
  src/components/column/Column.tsx
  src/components/getCard/GetCard.tsx
  src/components/getColumnData.tsx/GetColumnData.tsx
  src/components/hooks/useModal/useModal.tsx
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#65 [TK-59] fetch 인터셉터 구현
  src/api/AuthApi.ts
  src/api/dashboardsApi.ts
  src/api/membersApi.ts
  src/app/api/cookies/route.ts
  src/app/dashboard/[id]/edit/(Components)/DashboardName.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/app/dashboard/[id]/edit/page.tsx
  src/app/login/page.tsx
  src/middleware.ts
  src/utils/functionalFetch.ts
Labels: enhancement

#72 [TK-64] 대시보드에 컬럼 넣기
  .github/workflows/nextjs.yml
  src/api/cardApi.ts
  src/api/columnApi.ts
  src/app/dashboard/[id]/page.tsx
  src/components/Todo/TodoForm.tsx
  src/components/column/Column.tsx
  src/components/column/EditColumn.tsx
  src/components/getCard/GetCard.tsx
  tailwind.config.ts
Labels: enhancement

#76 [TK-53] 대시보드 해더 및 버그 수정
  src/api/membersApi.ts
  src/api/userApi.ts
  src/app/(home)/components/Landing.tsx
  src/app/dashboard/(components)/DashboardHeader.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteList.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteModal.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/app/dashboard/[id]/edit/page.tsx
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/layout.tsx
  src/components/Modal/Modal.tsx
  src/components/SideDashboardList/SideDashboardList.tsx
  src/components/header/Header.tsx
  src/context/DashboardContext.tsx
  src/utils/functionalFetch.ts
Labels: enhancement

#80 [TK-78] redirection client, server
  src/api/columnApi.ts
  src/api/dashboardsApi.ts
  src/api/membersApi.ts
  src/app/dashboard/(components)/DashboardHeader.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteList.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/app/dashboard/[id]/page.tsx
  src/utils/functionalFetch.ts
Labels: enhancement

#89 [TK-83] 랜딩 페이지 수정
  .eslintrc.cjs
  package-lock.json
  package.json
  public/images/github.png
  public/images/refresh-white.svg
  public/images/refresh.svg
  src/app/(home)/components/Canvas3DView.tsx
  src/app/(home)/components/Footer.tsx
  src/app/(home)/components/Landing.tsx
  src/app/(home)/page.tsx
  src/app/dashboard/(components)/DashboardHeader.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardBack.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteModal.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/components/hooks/useMediaQuery.ts
  src/middleware.ts
  tailwind.config.ts
Labels: enhancement

#94 [Tk 39] 계정관리 페이지 기능 구현
  public/images/pofileimg-plus.svg
  src/api/AuthApi.ts
  src/api/userApi.ts
  src/app/login/(components)/Login.tsx
  src/app/login/page.tsx
  src/app/mypage/(components)/MyProfile.tsx
  src/app/mypage/(components)/Mypassword.tsx
  src/app/mypage/page.tsx
  src/app/signup/(components)/Signup.tsx
  src/app/signup/page.tsx
  src/components/login/InputUserInfo.tsx
  src/components/mypage/myaccounts.tsx
Labels: enhancement

#106 [TK-101] style 격변
  public/images/taskify-logo-light.svg
  public/images/taskify-logo-main.svg
  public/images/taskify.svg
  src/app/(home)/components/Canvas3DView.tsx
  src/app/(home)/components/Landing.tsx
  src/app/(home)/page.tsx
  src/app/dashboard/(components)/DashboardHeader.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardBack.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardName.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteList.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/app/dashboard/[id]/edit/page.tsx
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/mydashboard/(components)/InvitationDashboard/InvitationList.tsx
  src/app/dashboard/mydashboard/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/(components)/MyProfile.tsx
  src/app/mypage/(components)/Mypassword.tsx
  src/components/SideDashboardList/SideDashboardList.tsx
  src/components/header/Header.tsx
  src/components/login/InputUserInfo.tsx
  src/components/login/LoginLink.tsx
  tailwind.config.ts
Labels: enhancement

#107 [TK-104] 무한스크롤
  src/api/cardApi.ts
  src/api/columnApi.ts
  src/app/dashboard/[id]/page.tsx
  src/components/column/AddColumn.tsx
  src/components/column/Column.tsx
  src/components/getCard/GetCard.tsx
  tailwind.config.ts
Labels: enhancement

#118 [TK-111] 랜딩 페이지 스타일 적용
  README.md
  public/images/refresh-white.svg
  src/app/(home)/components/Canvas3DView.tsx
  src/app/(home)/components/Landing.tsx
  src/app/(home)/page.tsx
  src/app/dashboard/(components)/DashboardHeader.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardName.tsx
  src/app/dashboard/[id]/edit/(Components)/LinkComponents.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/SideDashboardList/SideDashboardCard.tsx
  src/components/column/EditColumn.tsx
  src/components/header/Header.tsx
Labels: enhancement

#121 [Tk 39] 로그인 회원가입 유효성 수정
  src/api/AuthApi.ts
  src/api/userApi.ts
  src/app/dashboard/(components)/DashboardHeader.tsx
  src/app/login/(components)/Login.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/(components)/Signup.tsx
  src/components/login/InputUserInfo.tsx
Labels: enhancement

#124 [TK-111] 디자인 통일 및 미비사항 총 정리
  public/images/mokoko-cry.png
  public/images/mokoko-smile.png
  public/images/mokoko-stop2.png
  public/images/plus-icon.svg
  public/images/profileimg-plus.svg
  src/app/(home)/components/Landing.tsx
  src/app/dashboard/(components)/DashboardHeader.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardBack.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardDelete.tsx
  src/app/dashboard/[id]/edit/(Components)/DashboardName.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteList.tsx
  src/app/dashboard/[id]/edit/(Components)/InviteModal.tsx
  src/app/dashboard/[id]/edit/(Components)/MemberList.tsx
  src/app/dashboard/[id]/edit/page.tsx
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/mydashboard/(components)/InvitationDashboard/InvitationDashboard.tsx
  src/app/dashboard/mydashboard/(components)/InvitationDashboard/InvitationList.tsx
  src/app/dashboard/mydashboard/(components)/InvitationDashboard/SearchForm.tsx
  src/app/dashboard/mydashboard/(components)/MydashboardSection/DashboardList.tsx
  src/app/dashboard/mydashboard/page.tsx
  src/app/mypage/(components)/MyProfile.tsx
  src/app/mypage/(components)/Mypassword.tsx
  src/app/mypage/page.tsx
  src/components/SideDashboardList/SideDashboardList.tsx
  src/components/column/Column.tsx
  src/components/login/MainLogo.tsx
Labels: enhancement

#129 [Tk 39] 로그인, 회원가입, 계정관리 페이지 최종 수정
  src/api/AuthApi.ts
  src/api/userApi.ts
  src/app/login/(components)/Login.tsx
  src/app/login/page.tsx
  src/app/mypage/(components)/MyProfile.tsx
  src/app/mypage/(components)/Mypassword.tsx
  src/app/mypage/page.tsx
  src/app/signup/(components)/Signup.tsx
  src/app/signup/page.tsx
  src/components/login/InputUserInfo.tsx
  src/components/login/LoginLink.tsx
  src/components/login/MainLogo.tsx
Labels: enhancement

#132 [TK-108 ]컬럼 간 드래그앤드롭
  next.config.js
  package-lock.json
  package.json
  src/api/columnApi.ts
  src/app/dashboard/[id]/page.tsx
  src/components/column/Column.tsx
Labels: enhancement
